/**
 * title
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ap.client.api;

import com.ap.client.ApiException;
import com.ap.client.model.Per;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Get 1 day nm_perf data
     *
     * Get 1 day nm_perf data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmPerf1dayGetTest() throws ApiException {
        String username = null;
        String password = null;
        // Per response = api.nmPerf1dayGet(username, password);

        // TODO: test validations
    }
    
    /**
     * Get 2 hour nm_perf data
     *
     * Get 2 hour nm_perf data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmPerf2hourGetTest() throws ApiException {
        String username = null;
        String password = null;
        // Per response = api.nmPerf2hourGet(username, password);

        // TODO: test validations
    }
    
    /**
     * Get 30 minutes nm_perf data
     *
     * Get 30 minutes nm_perf data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmPerf30minGetTest() throws ApiException {
        String username = null;
        String password = null;
        // Per response = api.nmPerf30minGet(username, password);

        // TODO: test validations
    }
    
    /**
     * Get 5 minutes nm_perf data
     *
     * Get 5 minutes nm_perf data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmPerf5minGetTest() throws ApiException {
        String username = null;
        String password = null;
        // Per response = api.nmPerf5minGet(username, password);

        // TODO: test validations
    }
    
    /**
     * Get all performance info.
     *
     * Get all performance info.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void nmPerfsGetTest() throws ApiException {
        String username = null;
        String password = null;
        // Per response = api.nmPerfsGet(username, password);

        // TODO: test validations
    }
    
}
